#!/usr/bin/env python3
"""
View recent dreams generated by VALIS agents
"""
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

from memory.db import db

def view_recent_dreams():
    dreams = db.query("""
        SELECT p.name, ul.dream_type, ul.content, ul.symbolic_weight, 
               ul.emotional_resonance, ul.archetype_tags, ul.timestamp
        FROM unconscious_log ul
        JOIN persona_profiles p ON ul.agent_id = p.id
        ORDER BY ul.timestamp DESC
        LIMIT 5
    """)
    
    print("=== RECENT DREAMS FROM VALIS AGENTS ===")
    
    for dream in dreams:
        print(f"\n[{dream['name']}] - {dream['dream_type'].upper()}")
        print(f"Time: {dream['timestamp']}")
        print(f"Content: {dream['content']}")
        print(f"Symbolic Weight: {dream['symbolic_weight']:.3f}")
        print(f"Emotional Resonance: {dream['emotional_resonance']:.3f}")
        print(f"Archetypes: {dream['archetype_tags']}")
        print("-" * 80)

if __name__ == "__main__":
    view_recent_dreams()
